# dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6-dev"
os:
  - osx
osx_image: 
  - xcode8.3
before_install:

  - wget https://repo.continuum.io/archive/Anaconda3-2019.03-MacOSX-x86_64.sh -O Anaconda.sh
  - chmod +x Anaconda.sh
  - ./Anaconda.sh -b
  - export PATH=/home/travis/anaconda3/bin:$PATH
  - conda update --yes conda

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda env create --yes -f environment.yml
  

  # Below, include the dependencies you want to install with conda, optionally
  # specifying versions used in the matrix above. If you split this into
  # multiple conda install commands, you should always include numpy=$NUMPY as
  # the first package to install (for every conda install command) otherwise
  # numpy may be automatically upgraded.
  - conda activate d
  # You can also install some dependencies with pip if not available in conda

  # - pip install ...

script:
  - pytest
  # - py.test  # will run all tests in the package